version = "1.0"

[main]
name = "Minecraft configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.gamemode]
        ask = "Gamemode"
        type = "select"
        choices = ["survival", "creative", "adventure", "spectator"]
        default = "survival"
        help = "Choose the default gamemode on your server."
        bind = "gamemode:/var/www/__APP__/server.properties"

        [main.config.level_seed]
        ask = "World seed"
        type = "string"
        help = "Choose the seed used on your server (leave blank for a random seed)."
        bind = "level-seed:/var/www/__APP__/server.properties"